MvcAWSApiComicsMySql/Models/Comic.cs
namespace MvcAWSApiComicsMySql.Models
{
    public class Comic
    {
        public int IdComic { get; set; }
        public string Nombre { get; set; }  
        public string Imagen { get; set; }


    }
}

MvcAWSApiComicsMySql/Models/ErrorViewModel.cs
namespace MvcAWSApiComicsMySql.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MvcAWSApiComicsMySql/Controllers/ComicsController.cs
using Microsoft.AspNetCore.Mvc;
using MvcAWSApiComicsMySql.Models;
using MvcAWSApiComicsMySql.Services;

namespace MvcAWSApiComicsMySql.Controllers
{
    public class ComicsController : Controller
    {
        private ServiceApiComics service;

        public ComicsController(ServiceApiComics service)
        {
            this.service = service;
        }

        public async Task<IActionResult> Index()
        {
            List<Comic> comics = await this.service.GetComicsAsync();
            return View(comics);
        }

        public async Task<IActionResult> Details(int id)
        {
            Comic comic = await this.service.FindComicAsync(id);
            return View(comic);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Comic comic)
        {
            await this.service.CreateComic(comic);
            return RedirectToAction("Index");
        }

    }
}

MvcAWSApiComicsMySql/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MvcAWSApiComicsMySql.Models;
using System.Diagnostics;

namespace MvcAWSApiComicsMySql.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MvcAWSApiComicsMySql/Views/Comics/Create.cshtml
@model MvcAWSApiComicsMySql.Models.Comic

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Comic</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="IdComic" class="control-label"></label>
                <input asp-for="IdComic" class="form-control" />
                <span asp-validation-for="IdComic" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Imagen" class="control-label"></label>
                <input asp-for="Imagen" class="form-control" />
                <span asp-validation-for="Imagen" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MvcAWSApiComicsMySql/Views/Comics/Details.cshtml
@model MvcAWSApiComicsMySql.Models.Comic

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Comic</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdComic)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdComic)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            <img src="@Model.Imagen" style="width:100px;height:100px">
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Imagen)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

MvcAWSApiComicsMySql/Views/Comics/Index.cshtml
@model IEnumerable<MvcAWSApiComicsMySql.Models.Comic>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IdComic)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Imagen)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IdComic)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                <img src="@item.Imagen" style="width:100px;height:100px">
            </td>
            <td>
                    <a class="nav-link text-dark"
                   asp-area=""
                   asp-controller="Comics"
                   asp-action="Details" 
                   asp-route-id="@item.IdComic">DETALLES</a>
            </td>
        </tr>
}
    </tbody>
</table>

MvcAWSApiComicsMySql/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MvcAWSApiComicsMySql/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcAWSApiComicsMySql</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MvcAWSApiComicsMySql.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcAWSApiComicsMySql</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                       
                        <li class="nav-item">
                            <a class="nav-link text-dark"
                            asp-area="" 
                            asp-controller="Comics"
                            asp-action="Index">Comics</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MvcAWSApiComicsMySql - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>